Create neofetch.py
Dragon-Userbot/custom_modules pull request #30
Opened 2022-01-19 14:06 UTC by TupaBan-Dev

2022-01-19 14:06 UTC, iamnalinor commented
@TupaBan-Dev ого

2022-02-12 19:16 UTC, john-phonk commented
нерабочий модуль 
не соответствует dragon v3.*

2022-02-12 19:35 UTC, fuccsoc requested changes
incompatible with 3.0

2022-03-23 06:03 UTC, iamnalinor commented
Won't work on Linux and current Dragon-Userbot version. Closed.

2022-03-23 06:03 UTC, closed without merging

2022-03-23 06:03 UTC, ahmedov777-ai commented
@iamnalinor Круто

2022-03-23 08:31 UTC, lkqas commented
@ahmedov777-ai Ахуенно