Create compressor.py
Dragon-Userbot/custom_modules pull request #39
Opened 2022-03-17 08:57 UTC by AbhiTheModder

Hello i got this script from Ultroid team please check if this script can run in dragon too if not then i've to write a new script and if worked then my work became easy 😅

2022-03-17 09:03 UTC, john-phonk commented
**No, this module will not work in dragon**

Dragon custom module example:

```python3
from pyrogram import Client, filters
from pyrogram.types import Message
from utils.misc import modules_help, requirements_list, prefix


# packages from PyPI
# import example_1
# import example_2


@Client.on_message(filters.command("example_edit", prefix) & filters.me)
async def example_edit(client: Client, message: Message):
    await message.edit("<code>This is an example module</code>")


@Client.on_message(filters.command("example_send", prefix) & filters.me)
async def example_send(client: Client, message: Message):
    await client.send_message(message.chat.id, "<b>This is an example module</b>")


# This adds instructions for your module
modules_help.append(
    {"example": [{"example_send": "example send"}, {"example_edit": "example edit"}]}
)

# If your custom module requires packages from PyPI, write the names of the packages in these functions
# requirements_list.append('example_1')
# requirements_list.append('example_2')
# etc
```

2022-03-17 09:05 UTC, AbhiTheModder commented
Okay then i 've to write my own script

2022-03-17 09:08 UTC, AbhiTheModder commented
So one question also if i make a script how i could check that before creating pr and disturbing the team ?

2022-03-17 09:11 UTC, john-phonk commented
Place your module in modules/custom_modules directory and restart userbot

2022-03-17 09:12 UTC, AbhiTheModder commented
OKay thanks very much

2022-03-17 16:40 UTC, iamnalinor requested changes

2022-03-17 16:45 UTC, AbhiTheModder commented on exceptions.py
> +from pyrogram.types import Message, User
okay adding everything from exceptions to gban file

2022-03-17 16:45 UTC, AbhiTheModder commented on exceptions.py
> +            await message.edit("__No Permissions to restrict Members__")
okay

2022-03-17 16:47 UTC, AbhiTheModder commented on exceptions.py
> +async def CheckAdmin(message: Message):
not understood this can you explain a bit

2022-03-17 17:20 UTC, AbhiTheModder commented on exceptions.py
> +from pyrogram.types import Message, User
i'm confused fully now i'll try tomorrow again and will tell when added things from exceptions it given `name must an instance of str`

2022-03-18 10:56 UTC, AbhiTheModder commented on exceptions.py
> +from pyrogram.types import Message, User
hello i've moved exception to custom_module now itll take things from exceptions.py custom_module which user need install first as moving those thigs inside one file giving me errors

2022-03-18 10:57 UTC, AbhiTheModder commented on exceptions.py
> +from pyrogram.types import Message, User
and this module is working very perfectly i checked 5 times

2022-03-23 05:57 UTC, merged